spring.application.name=WS-Chat

server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645103466B5970
jwt.expiration-ms=86400000

logging.level.com.chat=DEBUG
